### ISSUE TITLE
Consider making accept return a socket, async_accept pass the socket to the handler

### ISSUE THREAD

**Issue by chriskohlhoff** [chriskohlhoff/asio-tr2#128]
However keep passing endpoint as reference.

**Comment by chriskohlhoff** [comment]
Unfortunately the obvious approach cannot work without breaking socket type safety.

Right now, a basic_datagram_socket is-a basic_socket, and a basic_stream_socket is-a basic_socket. However, one cannot go downwards from basic_socket to one or other of those types.

A basic_socket_acceptor can be used with either type of socket, i.e. one can accept either stream-oriented or datagram-oriented sockets depending on the protocol (although not UDP, but other protocols may).

So a hypothetical new version of this accept() would have to return basic_socket, but this cannot be down-converted to either type. In addition, the basic_socket destructor would have to be made public (and presumably virtual).

An alternative approach: we have to add the socket typedef to the Protocol type requirements, or perhaps add a new AcceptableProtocol as type requirements that extend Protocol by adding the socket typedef. The return type of accept would then be Protocol::socket.

**Comment by chriskohlhoff** [comment]
Would also seem to inhibit having the accepted socket on a different io_service to the acceptor.

**Comment by chriskohlhoff** [comment]
## Pre-Lenexa Summary

[[socket.acceptor]](http://open-std.org/JTC1/SC22/WG21/docs/papers/2015/n4478.html#socket.acceptor)

I really like this change as it simplifies and shortens common use cases.

The `basic_socket_acceptor` class's `accept` and `async_accept` member functions have been changed to produce the incoming socket object by moving the result, rather than by taking a socket object by non-const reference. For example, a synchronous accept operation may now look like this:

```
tcp::socket socket(my_acceptor.accept());
// read and write on newly accepted socket ...
```

and an asynchronous accept operation like this:

```
my_acceptor.async_accept(
    [](error_code ec, tcp::socket socket)
    {
      if (!ec)
      {
        // read and write on newly accepted socket
      }
    });
```

By default, the newly accepted socket uses the same `io_service` as the acceptor. However, an alternate `io_service` can be specified:

```
  my_acceptor.async_accept(my_io_service,
    [](error_code ec, tcp::socket socket)
    {
      if (!ec)
      {
        // read and write on newly accepted socket
      }
    });
```

This is required to support io_service-per-CPU designs, for example.

To facilitate this change, new `AcceptableProtocol` type requirements have been introduced, which extend the `Protocol` type requirements by adding the `socket` nested typedef.

As a consequence of this change, the `basic_socket_streambuf` class no longer inherits from `basic_socket` — it did so previously to allow users to pass it to `accept()` or `async_accept()`. Instead, `basic_socket_streambuf` and `basic_socket_iostream` are move-enabled and support the ability to move-construct from a socket:

```
tcp::iostream s(my_acceptor.accept());
```

The change was included in revision 5. An implementation can be found on the master branch of Asio's [GitHub repository](https://github.com/chriskohlhoff/asio).

**Comment by mcbp223** [comment]
Hello, until this gets implemented, I would like to use the move operator= of the base class basic_socket, so I could reuse an iostream with a new connection, like
```java
basic_socket<tcp, tcp::socket::service_type>& base = *ios.rdbuf();
base = std::move(newsocket);
```
What would I need to do to make this work as intended? In my tests the iostream doesn't seem to close the newly moved socket, then things get out of sync quick.

**Comment by jwakely** [comment]
@mcbp223 until this gets implemented where? This repository (and issue tracker) is for the C++ Networking TS document, not for an implementation. The changes described above where made to the document a long time ago (and this issue should probably have been closed at that time).

If you're asking about Asio then this is the wrong place.
