### ISSUE TITLE
Document should probably not refer to deprecated function `gethostbyname`

### ISSUE THREAD

**Issue by mclow** [chriskohlhoff/asio-tr2#13]
We wouldn't want people to implement it that way.

See https://threatpost.com/enterprise-apps-in-scope-of-ghost-glibc-vulnerability/110909 and http://threatpost.com/ghost-glibc-remote-code-execution-vulnerability-affects-all-linux-systems/110679 for more about why we don't want people using `gethostbyname`.

**Comment by chriskohlhoff** [comment]
Which section are you looking at?

**Comment by mclow** [comment]
Marshall can't read. Section "9.11.22. Host name functions" refers to `gethosthame`
