### ISSUE TITLE
Question about read()

### ISSUE THREAD

**Issue by mclow** [chriskohlhoff/asio-tr2#14]
There are four overloads of `read()` defined in section 10.8.19.

```
read(stream, buffers);
read(stream, buffers, error);
read(stream, buffers, completion);
read(stream, buffers, completion, error);
```
- What is the difference in behavior between the versions that take an `error_code` and the ones that do not? [ My guess is that when the error code is non-zero, they throw it, but the spec doesn't say that ]
- If that is true, should the versions that take an error code be `noexcept`?

The same questions apply to `write()`

**Comment by chriskohlhoff** [comment]
> What is the difference in behavior between the versions that take an error_code and the ones that do not? [ My guess is that when the error code is non-zero, they throw it, but the spec doesn't say that ]

Your guess is right. There are blanket rules specified in section 10.2.1 [err.report.sync].

> If that is true, should the versions that take an error code be noexcept?

I'd say probably not, for the same reason that the std algorithms in `<algorithm>` are not. I.e. operations on the template arguments may throw. It's up to the caller whether they use types that do or do not throw.

**Comment by mclow** [comment]
Ok, that makes sense to me. Thanks.
