### ISSUE TITLE
Please give each section in the proposal a name as well as a number

### ISSUE THREAD

**Issue by mclow** [chriskohlhoff/asio-tr2#2]
In the standard, every section has a unique name such as `[container.requirements]`. (and the section names are hierarchical)

Sometimes sections get renumbered, but the name acts as a “unique identifier” for the section.
More practically, the LWG issue tools use the section names to group issues, and the libc++ test suite is organized according to section name.

So, "10.13.4. Class ip::address” could have a name of `[ip.address]`
followed by `[ip.address.address_v6]` and `[ip.address.address_v4]`

I think this will make the review go easier (and make tracking changes across revisions simpler, too)

**Comment by chriskohlhoff** [comment]
Fixed in 72d8c3e49992afc412a2d3f032acd0fbbf486513.
