### ISSUE TITLE
basic_socket::at_mark(error_code&) doesn't say what it returns on error

### ISSUE THREAD

**Issue by jwakely** [chriskohlhoff/asio-tr2#204]
The Filesystem TS deals with this like:

> The signature with argument `ec` returns false if an error occurs.

basic_socket::available() says "or 0 if an error occurs" which isn't clear whether that applies to both overloads, or only the one taking an error_code.

**Comment by chriskohlhoff** [comment]
Can the rules in [err.report.sync] be tweaked to cover this so we don't have to repeat this formulation everywhere? (Perhaps it already does cover it but could be made clearer.)

**Comment by chriskohlhoff** [comment]
Sorry, didn't read carefully enough.... I realise now what you're saying. At_mark is missing the return specification.

**Comment by chriskohlhoff** [comment]
Fixed at_mark in 8761408d6124099703ff8105dca82f18b489475c.
Let me know if you think [err.report.sync] should also be changed.

**Comment by jwakely** [comment]
I think [err.report.sync] is clear enough, and does cover cases like basic_socket::available(). Thanks
