### ISSUE TITLE
[internet.endpoint.io] uses protocol_type typedef in scope where it isn't declared

### ISSUE THREAD

**Issue by jwakely** [chriskohlhoff/asio-tr2#214]
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0112r0.html#internet.endpoint.io describes the effects in terms of:

```
if (ep.protocol() == protocol_type::v6())
```

but `protocol_type` is not defined here. I assume it should be `_InternetProtocol` or `basic_endpoint<_InternetProtocol>::protocol_type`

**Comment by chriskohlhoff** [comment]
Fixed in 3fba5ff22212819b5f190dde3a248ce37a0d8318.
