### ISSUE TITLE
address_v4 comparison operators should be defined in terms of op== and op<

### ISSUE THREAD

**Issue by mclow** [chriskohlhoff/asio-tr2#3]
In the standard, when we define a full set of comparison operators, we usually define them all in terms of < and ==.  If you look at the relational operators for <optional> in N4336, you’ll see what I mean.

Note that this is already the case for `address_v6`

**Comment by chriskohlhoff** [comment]
Fixed in 0cacdd1592740e45909d4ec7fcda21e76a36f953.
