### ISSUE TITLE
use typedefs that you've declared 

### ISSUE THREAD

**Issue by mclow** [chriskohlhoff/asio-tr2#5]
In the address_iteratorXX classes, you have 

```
typedef const addressXX* pointer;
typedef const addressXX& reference;
```

but then you define functions thus:

```
const addressXX& operator*
const addressXX* operator->
```

The return types of these functions should be `reference` and `pointer`.

**Comment by chriskohlhoff** [comment]
Fixed in 339b6b6cf570ceb088dd6a9d30c25cd19a67c26b.
